# Generated by Django 4.0.4 on 2022-07-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryaa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reg',
            new_name='Form',
        ),
    ]
